### ISSUE TITLE
Homepage page template gone from options

### ISSUE THREAD

**Issue by mattiasaxell** [openknowledge-archive/wordpress-theme-with-bp#33]
After re-design of Wordpress theme the page we had at http://se.okfn.org/ like http://okfn.org got changed into a blog-format page. Is there any way to restore this? The page is still there and set as front page but is somehow replaced by blog. 
Related to this I have been in touch with @tlacoyodefrijol and @morchickit over e-mail who started Trello issue about the following:

The two options for clean page template when adding new pages also seems gone. E.g. we used to have a localized version in Swedish of https://okfn.org/about/ but as you can see, the current page template now forces right sidebar which messes up the layout - http://se.okfn.org/about/
- Is it possible to restore the other template which does not force sidebar? I think it was called Homepage. The other one which is left is Default template.

**Comment by pwalsh** [comment]
@mattiasaxell yes.

So we will have:
- the current layout options
- a new layout template which is the same as the current "content" pages, but can have the sidebar removed
- the ability to set a different page as the home page, using the above template, and the blogfeed goes to /blog/

---

@gocemitevski do you understand the goals here? 

http://se.okfn.org/about/ is quite broken, and at present, http://se.okfn.org and http://se.okfn.org/blog/ are the same. This pattern is common for other sites too (move blog feed from homepage)

**Comment by pwalsh** [comment]
@gocemitevski 

before coding, please describe the template layout so we ensure we are all happy. Without knowing the current code myself, I imagine what we need in the end is:
- home page template
- blog list template
- blog page template
- general page template with sidebar
- general page template without sidebar
- ability to set blog list on home page, or on /blog/, in which case the home page template is used on home
- ability to add and remove widgets from the sidebar, applies to any template that uses it

obviously use all WP functionality as needed (there does not need to be this number of exact templates, just that a content editor can achieve the above easily) does that sound right? if not, please describe the alternative.

cc @morchickit

**Comment by pwalsh** [comment]
@gocemitevski this issue is the highest priority, as it has impact on sites across the network.

**Comment by gocemitevski** [comment]
@pwalsh will start working on it right away.

**Comment by gocemitevski** [comment]
@pwalsh here are the descriptions:
1. home page template:
   - similar to the blog layout, but it has advanced filtering of the loaded posts and uses specific category filters
   - always has a sidebar, which is the same sidebar used across the theme
   - it is never displayed in full width
2. blog list template
   - same as the home page template but with all posts shown in descending order
3. blog page template
   - same as any static page template with a sidebar
4. general page template with sidebar
   - same as any static page/blog page template with a sidebar
5. general page template without sidebar
   - a separate template without sidebar, so that the page content can be displayed in full width
6. ability to set blog list on home page, or on /blog/, in which case the home page template is used on home
   - this is already possible in the Reading Options
7. ability to add and remove widgets from the sidebar, applies to any template that uses it
   - this is already possible in the Widget Options

**Comment by pwalsh** [comment]
@gocemitevski most looks good, except your description of the home page template. See all my notes for you in https://trello.com/c/iOlkRyCn (private link). Home page can't be forced to have a sidebar, nor can it have a blog feed at all times, and, it definitely needs an area for just "content", either instead of, or, on top of, a blog feed.

**Comment by gocemitevski** [comment]
@pwalsh I currently don't have privileges to access the link.

**Comment by pwalsh** [comment]
@gocemitevski oh right, I changed the board that card is on last night. fixed now.

**Comment by gocemitevski** [comment]
@pwalsh I guess, this is what we're after for the Home page template?

![screen shot 2016-08-08 at 10 27 27](https://cloud.githubusercontent.com/assets/359855/17473813/dc3304b8-5d52-11e6-8f3c-e109f444a423.png)

**Comment by gocemitevski** [comment]
@mattiasaxell @pwalsh please confirm https://github.com/okfn/wordpress-theme/issues/33#issuecomment-238173119.

**Comment by pwalsh** [comment]
@gocemitevski please see my comments in the trello thread linked to. the main thing I see missing here is the ability to have a home page which is content only, and the above image does not address or answer that.

**Comment by gocemitevski** [comment]
@pwalsh please provide a link to the issue. I cannot seem to find it in my boards.

**Comment by pwalsh** [comment]
@gocemitevski https://github.com/okfn/wordpress-theme/issues/33#issuecomment-238163472

**Comment by mattiasaxell** [comment]
@gocemitevski The example you posted is like the blog overview which we have at
http://se.okfn.org/blog/

I'm thinking more like this one
https://okfn.org/opendata/how-to-open-data/ - but in the old style as it
was on okfn.org before the recent re-make. It is still that older style
on the network-sites. Potentially the code is still available in old
revisions?

**Comment by pwalsh** [comment]
@morchickit 

This was done. Can you check with the Network and see if there are any further requests.
