### ISSUE TITLE
title only on first page

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledge-archive/wordpress-theme-with-bp#5]
Check out http://okfn.be

There's home in `<h1>` on the first page. I cannot disable it. On the other pages, it's not there (which imo should be default behaviour)

Pieter

**Comment by pwalsh** [comment]
@gocemitevski pls check.

**Comment by gocemitevski** [comment]
@pwalsh that's because, in the old theme, a static WordPress page with a specific template was used as a homepage. We now have a dedicated template for the homepage, so this will not be an issue anymore. The title will adjust accordingly and Home will definitely will not show up.

But keep this issue open until we're completely sure.

**Comment by gocemitevski** [comment]
@pwalsh by the way, you can already test this on http://okfn.keitaro.info/.

**Comment by pwalsh** [comment]
FIXED.
