### ISSUE TITLE
Featured image not handled well by the new theme

### ISSUE THREAD

**Issue by nigelbabu** [openknowledge-archive/wordpress-theme-with-bp#8]
The new theme doesn't handle featured images well. It looks terrible at the moment. See http://au-okblogfarm-org.okf.staging.wpengine.com/blog/ for an example of what happens.

@mintcanary would you be able to offer some help on what's the best way to go about fixing it? I can work on fixing the actual issue if I know what's the best course of action :)

**Comment by lachlansimpson** [comment]
I think this is an issue in the get_the_post_thumbnail in content-blog.php? Somewhere in that chain it should request the feature image instead of the thumbnail if it exists, etc. I haven't spent enough time w WP recently to really get my hands dirty on this one, but that looks to be the most obvious problem.

**Comment by nigelbabu** [comment]
That's not the only problem. Even after it gets the right image, it's not handled well enough.

**Comment by smth** [comment]
Seems to me there are three key things that would improve this:
- Appropriately sized images need to be called (as previously identified)
- Less space could be allocated to the image (perhaps 1/3 rather than 1/2 of the page)
- A maximum width for the site as a whole would give you a finite maximum image size to work with, here and elsewhere on the site (as well as limit line lengths for text). 

Additionally:
- It's currently not obvious what post each image is associated with
- The large areas of white space are ugly and potentially confusing (one solution would be to make each post equal in height, including a placeholder image where required)

**Comment by lachlansimpson** [comment]
re point two, unsure which view of the image you are referring to, but on the blog list page, those images are _huge_, so I am a fan of making them more thumbnail sized. By which I mean a little smaller, not necessarily postage stamp size.

re your fouth point, I'm unsure in which context you are referring to wrt images - do you mean on the post's page or the blog page?

In relation to your final point I like the idea of "if image exists, float the intro text over the image" - similar to what I've done here (poorly, I'm no whizz, scroll down) http://www.skynoise.net/projects/
"else, just print the first paragraph" or something like that?

**Comment by ewan-klein** [comment]
Is this stalled? As far as I'm concerned, this problem is a showstopper in deploying the new theme.

**Comment by nigelbabu** [comment]
I'm waiting on Sam being assigned time to fix this issue. I'm aware it's a
show stopper.

Nigel Babu
Senior Sysadmin, Open Knowledge

**Comment by ewan-klein** [comment]
Thanks @nigelbabu for the clarification. The theme looks great otherwise and I'm really looking forward to using it.

**Comment by lachlansimpson** [comment]
Likewise: it looks great but we are waiting too.

Cheers

L.

**Comment by lachlansimpson** [comment]
Ok, I've dug some more into the code. It's hard, since the style.css is minimized, and I'm more comfortable with vim than TTW editing, and I can't change the php in the background, only the html in the browser.

It looks like it's delivering the 60x60 thumbnail instead of the main image. 
ie, instead of 
http://au.okblogfarm.org/files/2014/11/maggie-galea-team-e1427362625941.jpeg

it's serving 
http://au.okblogfarm.org/files/2014/11/maggie-galea-team-60x60.jpeg

This potentially could be solved by changing line 15 of content-blog.php from

```
echo '<a href="' . get_permalink() . '">' . get_the_post_thumbnail() . '</a>';
```

to 

```
echo '<a href="' . get_permalink() . '">' . get_the_post_thumbnail('large') . '</a>';
```

or 

```
echo '<a href="' . get_permalink() . '">' . get_the_post_thumbnail('medium') . '</a
```

Obv this isn't helped by our users uploading 5MB images with ridiculously large resolutions. But the 60x60 is bad. We need to up it a little bit, at least to medium or large. 

It's hard for me to tell - without access to the file system, I can't see what images are being created in http://au.okblogfarm.org/files/*

**Comment by nigelbabu** [comment]
Agreed. I'm waiting to see a better idea on how the list of posts should look. Our current default doesn't look good even with a larger image. I checked.

**Comment by PieterJanPauwels** [comment]
We have a similar situation. All our featured image source files have the same image ratio and size, but even then I turns out differently on our website:  http://www.openknowledge.be/updates/

**Comment by smth** [comment]
I've made a few changes [here](https://github.com/okfn/wordpress-theme/commit/6cfd86ba9e21e259c5e6c1e6b95bee33107e7e74), where it now looks like this: 
![blog](https://cloud.githubusercontent.com/assets/1375708/7029469/db846382-dd55-11e4-8709-f8a1f23bba81.jpg)

**Comment by PieterJanPauwels** [comment]
I do like @mintcanary's approach to working with images next to the title and intro, rather than above. Having the images above your title and intro takes up lots of space, requiring you to make a narrow 20:9 ratio image to keep room for text and retain a good UX. My only remark on the work is Sam, is that it would be be good to have the ability to put two blogposts next to each on desktop.

**Comment by lachlansimpson** [comment]
I like @mintcanary's too.

**Comment by nigelbabu** [comment]
Okay, pushed to staging. http://au-okblogfarm-org.okf.staging.wpengine.com/blog/

**Comment by nigelbabu** [comment]
@mintcanary The images are still too small. Is it something we can fix from the wordpress end or does the upload need to be larger images?

**Comment by smth** [comment]
It is fixed in the theme, however I found that I needed to re-add the images in order for Wordpress to generate them at the correct size.

This process may be automatable, with something like https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by nigelbabu** [comment]
Cheers, I'll test it out on one of the staging sites :)

**Comment by PieterJanPauwels** [comment]
We're using the new blog frontpage right now, great stuff! And way easier to just have a featured image with a 1:1 ratio. 
![screen shot 2015-05-07 at 16 10 16](https://cloud.githubusercontent.com/assets/6347860/7517147/9102afb8-f4d3-11e4-9b94-b09a3d7890ad.png)

**Comment by ewan-klein** [comment]
@nigelbabu  Is there any chance of testing the regenerate-thumbnails plugin that @mintcanary mentioned and, if it's successful, getting it installed? I don't think I will be able to re-upload all the featured images that I've currently got on the scot.okfn.org site. Or it would take quite a while to track them down. But I can confirm that re-uploading an image fixes the resolution problem.

**Comment by lachlansimpson** [comment]
+1 to this idea for same reason

**Comment by smth** [comment]
Really good to hear that this is working for you @PieterJanPauwels.

**Comment by Starl3n** [comment]
For the au site we don't have too many posts and feature images. I think reuploaded them would be fine for us. We can do the most recent ones first and work backwards with many hands making light work :)

**Comment by gocemitevski** [comment]
@pwalsh what's the current status of this issue?

**Comment by pwalsh** [comment]
@gocemitevski I'm closing it.
